FROM 192.168.3.253/library/tomcat8:v1
ADD target/glwlgwx /root/apache-tomcat-8.0.39/webapps/glwlgwx
ENTRYPOINT /root/apache-tomcat-8.0.39/bin/catalina.sh run
WORKDIR /root/apache-tomcat-8.0.39/webapps